Description: YAML Configuration file with dummy authentication parameters, deomnstrates format of what the authentication parameters should look like for your tenant
ProductNames:
  - teams
  - aad
M365Environment: commercial
Organization: abcdef.example.com
AppID: 0123456789abcdef01234566789abcde
CertificateThumbprint: fedcba9876543210fedcba9876543210fedcba98
