Description: |
  YAML Configuration file with all parameters
  This config file does not include any custom variables or any per product namespace variables
  For more specifc per product config variables please refer to the sample config associated with that product
  This example includes the following design choices for illustrative purposes:
  - Use of Pascal case convention for variable names
ProductNames:
  - teams
  - exo
  - defender
  - aad
  - sharepoint
M365Environment: commercial
OPAPath: .
LogIn: true
DisconnectOnExit: false
OutPath: .
OutFolderName: M365BaselineConformance
OutProviderFileName: ProviderSettingsExport
OutRegoFileName: TestResults
OutReportName: BaselineReports
Organization: abcdef.example.com
AppID: 0123456789abcdef01234566789abcde
CertificateThumbprint: fedcba9876543210fedcba9876543210fedcba98
