Description: | 
  YAML Typical Configuration File ( multiple products )
  Some names are commented out but for completeness are left in to show all product options
ProductNames:
  - teams
  # - exo
  # - defender
  - aad
  # - sharepoint
M365Environment: gcc
