# Purpose:  Run the workflow pipeline that tests the workflow code.

name: Run the Workflow Pipeline

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  # # Lint and Syntax Checks
  # lint-yaml:
  #   name: Lint
  #   uses: ./.github/workflows/lint_yaml.yaml
  # lint-powershell:
  #   name: Lint
  #   uses: ./.github/workflows/lint_powershell.yaml
  # # Security Checks
  # scan-secret:
  #   name: Security
  #   needs:
  #     - lint-yaml
  #     - lint-powershell
  #     - syntax-markdown
  #   uses: ./.github/workflows/run_secret_scan.yaml
  # check-security:
  #   name: Security
  #   needs:
  #     - lint-yaml
  #     - lint-powershell
  #     - syntax-markdown
  #   uses: ./.github/workflows/check_security.yaml
  # Unit Tests
  unit-workflow:
    name: Unit
    # needs:
    #   - scan-secret
    #   - check-security
    uses: ./.github/workflows/unit_test_workflows.yaml
